version: 2

builds:
  - ldflags: "-s -w"
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

scoops:
  - name: amnesia
    repository:
      name: scoop-bucket
      owner: cedws
      token: "{{ .Env.SCOOP_BUCKET_PUSH_TOKEN }}"

homebrew_casks:
  - name: amnesia
    repository:
      name: homebrew-tap
      owner: cedws
      token: "{{ .Env.HOMEBREW_TAP_PUSH_TOKEN }}"
    custom_block: |
      binary "amnesia", target: "age-plugin-amnesia"
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/amnesia"]
          end

changelog:
  use: github-native
